name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          scope: "@havenengineering"
      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.HAVEN_PLATFORM_BOT_PACKAGE_READ_PAT }}
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Notify via Microsoft Teams
        if: failure()
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MSTEAMS_WEBHOOK }}
          title: The build for migrate-contentful has failed.
          summary: The build for migrate-contentful has failed.
          text: >
            The build for `migrate-contentful` has failed. See https://github.com/HavenEngineering/migrate-contentful/actions.
          theme_color: FF0000
