name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@havenengineering"
      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.HAVEN_PLATFORM_BOT_PACKAGE_READ_PAT }}
      - name: Publish
        run: npm publish --unsafe-perm # See https://github.com/npm/npm/issues/3497
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify via Microsoft Teams
        if: failure()
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MSTEAMS_WEBHOOK }}
          title: Publishing module-haven-contentful-migration has failed.
          summary: Publishing module-haven-contentful-migration has failed.
          text: >
            Publishing `module-haven-contentful-migration` has failed. See https://github.com/HavenEngineering/module-haven-contentful-migration/actions.
          theme_color: FF0000
