name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@havenengineering"
      - name: Install
        run: npm ci
      - name: Publish
        run: npm publish --unsafe-perm # See https://github.com/npm/npm/issues/3497
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     - uses: actions/setup-node@v2
       with:
         registry-url: 'https://registry.npmjs.org'
     - name: Publish
       run: npm publish --unsafe-perm --access public
       env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
      - name: Notify via Microsoft Teams
        if: failure()
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MSTEAMS_WEBHOOK }}
          title: Publishing migrate-contentful has failed.
          summary: Publishing migrate-contentful has failed.
          text: >
            Publishing `migrate-contentful` has failed. See https://github.com/HavenEngineering/migrate-contentful/actions.
          theme_color: FF0000
